# Default values for firsthelm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

automountServiceAccountToken: false 

initContainers:
- image: rs06ue2dwscspthapps.azurecr.io/pslapi:dev_$(Build.BuildId)
  name: war
  command: ["cp", "/usr/local/artifact/presell.war", "/usr/local/tomcat/webapps/presell.war"]
  securityContext:
    readOnlyRootFilesystem : true
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 3000
  volumeMounts:
    - mountPath: /usr/local/tomcat/webapps/
      name: webapps
    - mountPath: /usr/local/tomcat/logs/
      name: log

image:
  repository: rs06ue2dwscspthapps.azurecr.io/pslapi:dev_$(Build.BuildId) 
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
 


podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: 
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem : true
  runAsUser: 1000
  runAsNonRoot: true
  capabilities:
    drop:
      - AUDIT_WRITE
      - FOWNER
      - FSETID
      - MKNOD
      - SETFCAP

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  limits:
    memory: "500Mi"
    cpu: "300m"
  requests:
    memory: "400Mi" 
    cpu: "100m"
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

volumeMounts:
- mountPath: /usr/local/tomcat/logs/
  name: log
#- mountPath: /usr/local/amai/
# name: amai  
- mountPath: /usr/local/tomcat/temp/
  name: temp
- mountPath: /usr/local/tomcat/webapps/
  name: webapps
- mountPath: /usr/local/tomcat/conf/Catalina/localhost
  name: catalina
- mountPath: /usr/local/tomcat/work/Catalina/localhost/presell
  name: catalina-localhost

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
